import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

interface ChannelReportData {
  channelName: string;
  subscribers: number;
  views: number;
  videos: number;
  revenue: number;
  revenueINR: number;
  rpm: number;
}

interface PDFReportOptions {
  title: string;
  subtitle?: string;
  brandName?: string;
  brandColor?: string;
  channels: ChannelReportData[];
  totalRevenue: number;
  totalRevenueINR: number;
  totalSubscribers: number;
  totalViews: number;
  exchangeRate: number;
  period: string;
  generatedBy: string;
}

export function generateMonthlyPDFReport(options: PDFReportOptions) {
  const doc = new jsPDF();
  const brandColor = options.brandColor || "#6366f1";
  const r = parseInt(brandColor.slice(1, 3), 16);
  const g = parseInt(brandColor.slice(3, 5), 16);
  const b = parseInt(brandColor.slice(5, 7), 16);

  doc.setFillColor(r, g, b);
  doc.rect(0, 0, 210, 35, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(options.brandName || options.title, 14, 18);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Monthly Revenue Report — ${options.period}`, 14, 28);

  doc.setTextColor(60, 60, 60);
  doc.setFontSize(9);
  const dateStr = new Date().toLocaleDateString("en-IN", { dateStyle: "long" });
  doc.text(`Generated: ${dateStr}`, 196, 28, { align: "right" });

  let y = 45;

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(40, 40, 40);
  doc.text("Summary", 14, y);
  y += 8;

  const summaryData = [
    ["Total Channels", String(options.channels.length)],
    ["Total Subscribers", options.totalSubscribers.toLocaleString()],
    ["Total Views", options.totalViews.toLocaleString()],
    ["Total Revenue (USD)", `$${options.totalRevenue.toFixed(2)}`],
    ["Total Revenue (INR)", `₹${options.totalRevenueINR.toLocaleString()}`],
    ["Exchange Rate", `1 USD = ₹${options.exchangeRate}`],
  ];

  autoTable(doc, {
    startY: y,
    head: [["Metric", "Value"]],
    body: summaryData,
    theme: "grid",
    headStyles: { fillColor: [r, g, b], fontSize: 9, fontStyle: "bold" },
    bodyStyles: { fontSize: 9 },
    columnStyles: { 0: { fontStyle: "bold", cellWidth: 60 }, 1: { cellWidth: 60 } },
    margin: { left: 14 },
    tableWidth: 120,
  });

  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 12;

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Channel-wise Revenue", 14, y);
  y += 4;

  autoTable(doc, {
    startY: y,
    head: [["#", "Channel", "Subscribers", "Views", "Revenue ($)", "Revenue (INR)", "RPM ($)"]],
    body: options.channels.map((ch, i) => [
      String(i + 1),
      ch.channelName,
      ch.subscribers.toLocaleString(),
      ch.views.toLocaleString(),
      `$${ch.revenue.toFixed(2)}`,
      `₹${ch.revenueINR.toLocaleString()}`,
      `$${ch.rpm.toFixed(2)}`,
    ]),
    theme: "striped",
    headStyles: { fillColor: [r, g, b], fontSize: 8, fontStyle: "bold" },
    bodyStyles: { fontSize: 8 },
    columnStyles: {
      0: { cellWidth: 8 },
      1: { cellWidth: 50 },
    },
    margin: { left: 14, right: 14 },
  });

  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;

  doc.setFontSize(7);
  doc.setTextColor(140, 140, 140);
  doc.text(`Report generated by ${options.generatedBy} | ${options.brandName || "InTubeMedia"} CMS`, 14, y);

  const filename = `${options.period.replace(/\s+/g, "-")}-Revenue-Report.pdf`;
  doc.save(filename);
}
